# Tensorflow 
> Tensor -----> mutli-dimension array (like numpy array )


Types of tensor (based on mutability):
    > Variable tensor ----> mutable
    > constant tensor ----->immutable

In [ ]:
# pip install tensorflow

In [1]:
import tensorflow as tf

In [2]:
t=tf.Variable(10)
print(t)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [8]:
t=tf.Variable(10,name='myscalar',dtype='float')
print(t)

<tf.Variable 'myscalar:0' shape=() dtype=float32, numpy=10.0>


In [9]:
print(t.numpy())            # userfriendly

10.0


In [5]:
t=tf.Variable([10,20,30.5])
print(t.numpy().size)

3


In [6]:
t=tf.Variable([[10,20],[30,40]])
print(t)
print(t.numpy())
print(t.shape)
print(t.numpy().size)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>
[[10 20]
 [30 40]]
(2, 2)
4


In [10]:
t=tf.constant([[10,20],[30,40]])
print(t)

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [11]:
print(t.numpy())

[[10 20]
 [30 40]]


In [12]:
t=tf.constant(10)
print(t)

tf.Tensor(10, shape=(), dtype=int32)


In [15]:
t*5   # new copy

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [14]:
print(t)

tf.Tensor(10, shape=(), dtype=int32)


In [16]:
t=tf.constant([10,20,30])
print(t)

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [17]:
print(t[0])

tf.Tensor(10, shape=(), dtype=int32)


In [18]:
# when try to assign a value 
t[0]=12

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [29]:
t=tf.Variable(10)
print(t)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [30]:
#t[0]=12

In [31]:
t.assign(12)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=12>

In [32]:
import tensorflow as tf

In [33]:
t=tf.random.normal(shape=(5,))     # mean=0, std=1 returns constant like tensor
print(t)

tf.Tensor([-0.55325097  1.867158   -1.354492   -2.3578808   0.12716755], shape=(5,), dtype=float32)


In [34]:
t=tf.random.normal(shape=(5,3))       # mean=0, std=1 returns constant like tensor
print(t)

tf.Tensor(
[[-1.8624078  -0.45330966  0.48219132]
 [ 0.29508096 -0.57185715  0.38419536]
 [-0.5009357   0.6367704  -0.6805105 ]
 [ 2.4214542   0.0086776   0.4908125 ]
 [-0.09741662  0.12668055  0.18884274]], shape=(5, 3), dtype=float32)


In [35]:
t=tf.random.truncated_normal(shape=(5,))  # mean=0, std=1 ,values must be with in 2std of mean
print(t)

tf.Tensor([-0.7061728   0.3798026   0.8393617  -0.48514012  0.8898756 ], shape=(5,), dtype=float32)


In [36]:
t=tf.random.truncated_normal(shape=(5,3))  # mean=0, std=1 ,values must be with in 2std of mean
print(t)

tf.Tensor(
[[ 0.15572949  0.7006498  -0.73870516]
 [ 0.6128455   0.05866168  0.60226995]
 [ 0.38284242 -0.10058033  1.890474  ]
 [-0.4779146   0.32186764 -0.34674844]
 [ 1.2044461  -1.0104126  -1.6739926 ]], shape=(5, 3), dtype=float32)


In [37]:
t=tf.random.uniform(shape=(5,)) # min=0, max=1, return constant like tensor from uniform dist
print(t)

tf.Tensor([0.80912566 0.4644549  0.33807003 0.46110868 0.42201316], shape=(5,), dtype=float32)


In [38]:
t=tf.random.uniform(shape=(5,), minval=5, maxval=10) # min=0, max=1, return constant like tensor from uniform dist
print(t)

tf.Tensor([5.1288896 8.393087  5.810673  5.233295  7.188408 ], shape=(5,), dtype=float32)


In [41]:
t=tf.random.uniform(shape=(3,3),minval=5,maxval=100 , dtype=tf.int32) # min=0, max=1, return constant like tensor from uniform dist
print(t)

tf.Tensor(
[[56 69 28]
 [36 27 21]
 [71 21 53]], shape=(3, 3), dtype=int32)


In [42]:
t=tf.random.uniform(shape=(10,),minval=1,maxval=100 , dtype=tf.int32) # min=0, max=1, return constant like tensor from uniform dist
print(t)

tf.Tensor([16  4 78 68 73  9 77 80  3  2], shape=(10,), dtype=int32)


In [43]:
# when we want to find the max element in our tensor
print(tf.math.reduce_max(t))

tf.Tensor(80, shape=(), dtype=int32)


In [44]:
print(tf.math.reduce_max(t))
print(tf.math.argmax(t))
print(tf.math.reduce_min(t))
print(tf.math.argmin(t))
print(tf.math.reduce_mean(t))
print(tf.math.reduce_sum(t))

tf.Tensor(80, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(41, shape=(), dtype=int32)
tf.Tensor(410, shape=(), dtype=int32)


In [45]:
t1=tf.random.uniform(shape=(3,3),minval=1,maxval=100,dtype=tf.int32) #returns constant like tensor from uniform dist
print(t1)

tf.Tensor(
[[79 54 34]
 [65 46 30]
 [34 91 91]], shape=(3, 3), dtype=int32)


In [46]:
t2=tf.random.uniform(shape=(3,3),minval=1,maxval=100,dtype=tf.int32) #returns constant like tensor from uniform dist
print(t2)

tf.Tensor(
[[73 43  5]
 [52 34 75]
 [89 51 73]], shape=(3, 3), dtype=int32)


In [47]:
tf.matmul(t1,t2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11601,  6967,  6927],
       [ 9807,  5889,  5965],
       [15313,  9197, 13638]])>

In [48]:
t1@t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11601,  6967,  6927],
       [ 9807,  5889,  5965],
       [15313,  9197, 13638]])>